# Numpy <hr style="border:2.5px solid #a8f9ffff"></hr>

<b>Francis Adrian R. Cernal</b>
<br>Computer Engineer

In [60]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [57]:
my_array = [1, 2, 3]
my_array

[1, 2, 3]

In [37]:
type(my_array)

list

In [38]:
my_array = np.array([1, 2, 3])

In [39]:
np.shape(my_array)

(3,)

# 2D Array

In [40]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.shape(my_array)

(2, 3)

In [42]:
trans_array = my_array.T

In [43]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.shape(trans_array)

(3, 2)

In [45]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [46]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [47]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], # Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]  # Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [48]:
np.shape(resistance)

(2, 11)

In [49]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [50]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [51]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [ ]:
#Mean
np.nanmean(resistance, axis = 1)

array([ 9.4 , 10.75])

In [53]:
jag_mean = np.nanmean(resistance, axis=0)[0]
pan_mean = np.nanmean(resistance, axis=1)[1]

print(f'Jaguar_Mean = {jag_mean:.2f} ohms')
print(f'Panther_Mean = {pan_mean:.2f} ohms')

Jaguar_Mean = 10.35 ohms
Panther_Mean = 10.75 ohms


In [54]:
#Meadian
np.nanmedian(resistance, axis=1)

array([9.8 , 9.55])

In [55]:
jag_median = np.nanmedian(resistance, axis=0)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print(f'Jaguar_Median = {jag_median:.2f} ohms')
print(f'Panther_Median = {pan_median:.2f} ohms')

Jaguar_Median = 10.35 ohms
Panther_Median = 9.55 ohms


In [62]:
#Mode
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [63]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [67]:
jag_res = resistance[0]

print("Jaguar_Mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar_Mode:
9.8 ohms
10.4 ohms


In [68]:
pan_res = resistance[1]

print("Panther_Mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther_Mode:
9.1 ohms


# Measures of Variability

In [70]:
#Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], # Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]  # Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [71]:
#Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [72]:
print(f'Jaguar_Range = {res_range[0]:.2f} ohms')
print(f'Panther_Range = {res_range[1]:.2f} ohms')

Jaguar_Range = 8.00 ohms
Panther_Range = 10.90 ohms


In [73]:
#1st Quartile
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [74]:
#2nd Quartile
res_Q2 = np.nanpercentile(resistance,50,axis=1)
res_Q2

array([9.8 , 9.55])

In [75]:
#3rd Quartile
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [79]:
#IQR
print(f'Jaguar_IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther_IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar_IQR = 1.05 ohms
Panther_IQR = 1.50 ohms


In [78]:
#Variance
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [81]:
print(f'Jaguar_Variance = {res_var[0]:.2f} ohms')
print(f'Panther_Variance = {res_var[1]:.2f} ohms')

Jaguar_Variance = 4.86 ohms
Panther_Variance = 11.08 ohms


In [82]:
#Standar Deviation
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])

In [83]:
print(f'Jaguar_Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther_Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar_Standard Deviation = 2.20 ohms
Panther_Standard Deviation = 3.33 ohms
